# Generated by Django 4.2.6 on 2023-11-14 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectionsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='item_fields',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
