# Generated by Django 4.2.6 on 2023-11-16 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectionsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='customfieldclass',
            constraint=models.UniqueConstraint(fields=('collection', 'name'), name='unique_custom_field_class'),
        ),
    ]
