# Generated by Django 4.2.6 on 2023-11-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0004_item_custom_fields_delete_customfield'),
        ('collectionsapp', '0002_customfieldclass_unique_custom_field_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='custom_fields_classes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='CustomFieldClass',
        ),
    ]
