# Generated by Django 4.2.6 on 2023-11-14 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectionsapp', '0002_collection_item_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='item_fields',
        ),
        migrations.AddField(
            model_name='collection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='collection_images/'),
        ),
        migrations.AddField(
            model_name='collection',
            name='image_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
