# Generated by Django 4.2.6 on 2023-11-14 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectionsapp', '0003_remove_collection_item_fields_collection_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='image_link',
        ),
        migrations.AddField(
            model_name='collection',
            name='custom_fields',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
