# Generated by Django 4.2.6 on 2023-11-15 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectionsapp', '0007_alter_collection_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='image',
        ),
        migrations.AddField(
            model_name='collection',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
