# Generated by Django 4.2.6 on 2023-11-16 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='customfield',
            constraint=models.UniqueConstraint(fields=('item', 'custom_field_class'), name='unique_custom_field'),
        ),
    ]
