# Generated by Django 4.2.6 on 2023-11-17 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0002_customfield_unique_custom_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='description',
        ),
    ]
