# Generated by Django 4.2.6 on 2023-11-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0003_remove_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='custom_fields',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='CustomField',
        ),
    ]
