# Generated by Django 4.2.6 on 2023-11-17 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0004_item_custom_fields_delete_customfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtag',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
