# Generated by Django 4.2.6 on 2023-11-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0005_alter_itemtag_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('collection', 'name'), name='unique_item'),
        ),
    ]
